version: '2'
services:
  capone-db:
    image: postgres:9.5.2
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: capone_test
  capone-api:
    command: npm run test
    build:
      context: ./
      dockerfile: docker/api.dock
    volumes:
      - .:/home/app/capone
      - /home/app/capone/node_modules
    links:
      - capone-db
    environment:
      NODE_ENV: test
      CAPONE_HOSTNAME: caponeapp.dev
      DATABASE_URL: postgres://root@capone-db/capone_test
      B2_ACCOUNT_ID: mockb2accountid
      B2_APPLICATION_KEY: mockb2applicationkey
      B2_BUCKET_ID: mockb2bucketid
      FASTLY_API_KEY: mockfastlyapikey
      FASTLY_SERVICE_ID: mockfastlyserviceid
