#!/bin/bash

set -e

if [ -d /usr/local/openresty ]; then
  exit 0
fi

sudo apt-get -y update
sudo apt-get -y install \
  build-essential \
  wget \
  libpcre3-dev \
  libssl-dev \
  libgeoip-dev \
  libpq-dev \
  nginx

# Download openresty
cd /usr/local
wget https://openresty.org/download/ngx_openresty-1.9.3.2.tar.gz
tar -xzvf ngx_openresty-1.9.3.2.tar.gz
rm ngx_openresty-1.9.3.2.tar.gz

# Install openresty
cd ngx_openresty-1.9.3.2
./configure \
  --sbin-path=/usr/sbin/nginx \
  --conf-path=/etc/nginx/nginx.conf \
  --error-log-path=/var/log/nginx/error.log \
  --http-client-body-temp-path=/var/lib/nginx/body \
  --http-fastcgi-temp-path=/var/lib/nginx/fastcgi \
  --http-log-path=/var/log/nginx/access.log \
  --http-proxy-temp-path=/var/lib/nginx/proxy \
  --http-scgi-temp-path=/var/lib/nginx/scgi \
  --http-uwsgi-temp-path=/var/lib/nginx/uwsgi \
  --lock-path=/var/lock/nginx.lock \
  --pid-path=/var/run/nginx.pid \
  --with-luajit \
  --with-http_dav_module \
  --with-http_flv_module \
  --with-http_geoip_module \
  --with-http_gzip_static_module \
  --with-http_realip_module \
  --with-http_stub_status_module \
  --with-http_ssl_module \
  --with-http_sub_module \
  --with-ipv6 \
  --with-sha1=/usr/include/openssl \
  --with-md5=/usr/include/openssl \
  --with-http_stub_status_module \
  --with-http_secure_link_module \
  --with-http_sub_module \
  --with-http_postgres_module

make
sudo make install
rm -rf /usr/local/ngx_openresty-1.9.3.2*
